---
- name: Install Horizon Client on RedHat Systems
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Install Horizon Client on Windows Systems
  include_tasks: windows.yml
  when: ansible_os_family == "Windows"
...
